---
title: "churnvol2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(caret)
library(plyr)
library(randomForest)
library(psych)
library(corrplot)
library(e1071)
library(ROCR)
```
```{r}

for (i in 1:ncol(combined)){
  combined[,i] <- as.factor(combined[,i])
}

combined$tenure <- as.integer(combined$tenure)
combined$MonthlyCharges <- as.integer(combined$MonthlyCharges)
combined$TotalCharges <- as.integer(combined$TotalCharges)

# Removing values with high Pr
highpr_vars <- c("PaymentMethodMailed check", "PaymentMethodCredit card (automatic)", "StreamingMoviesYes", "DeviceProtectionYes", "OnlineBackupYes", "genderFemale", "Partner1", "Dependents1", "StreamingTVYes")

combined <- combined[,!(names(combined) %in% highpr_vars)]

traindata1 <- createDataPartition(y = combined$ChurnYes, p = 0.75, list = FALSE)
train1 <- combined[traindata1,]
test1 <- combined[-traindata1,]

train100 <- train1[1:3000,]
```


```{r}
set.seed(205)

fit1 <- glm(ChurnYes~., data = combined, family = binomial)
summary(fit1)

churn_probs1 <- predict(fit1, test1, type = "response")
head(churn_probs1)
```
```{r}
glm_pred1 = rep("No", length(churn_probs1))
glm_pred1[churn_probs1 > 0.5] = "Yes"
glm_pred1 <- as.factor(glm_pred1)
```
```{r}
pred1 <- prediction(churn_probs1, test1$ChurnYes)
prf1 <- performance(pred1, measure = "tpr", x.measure = "fpr")
plot(prf1)
```
```{r}
auc1 <- performance(pred1, measure = "auc")
auc1 <- auc1@y.values[[1]]
auc1
```





